version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 53794:1972
      - 53796:52773
      - 8080:8080
      - 50051:50051
      - 53773
    volumes:
      - ./:/irisdev/app